#!/bin/bash
source var-task1.sh
# Create a resource group.
az group create \
  --name $RgName \
  --location $Location

# Create a virtual network with a subnet.
az network vnet create \
  --name $Vnetname \
  --resource-group $RgName \
  --location $Location \
  --address-prefix $addressprefix \
  --subnet-name $subnetname \
  --subnet-prefix $subnetprefix


# Create a network security group for the subnet.
az network nsg create \
  --resource-group $RgName \
  --name $nsgname \
  --location $Location

# Create an NSG rule to allow ssh traffic in from the Internet to the subnet.
az network nsg rule create \
  --resource-group $RgName \
  --nsg-name $nsgname \
  --name $nsgrulename \
  --access Allow \
  --protocol Tcp \
  --direction Inbound \
  --priority $priority \
  --source-address-prefix Internet \
  --source-port-range "*" \
  --destination-address-prefix "*" \
  --destination-port-range 22

# Associate the front-end NSG to the  subnet.
#az network vnet subnet update \
 # --vnet-name vnet1 \
 # --name subnet1 \
 # --resource-group $RgName \
 # --network-security-group MyNsg-subnet1


# Create a public IP address for the web server VM.
az network public-ip create \
  --resource-group $RgName \
  --name $publicIPname

# Create a Web Server VM in the front-end subnet.
az vm create \
  --resource-group $RgName \
  --name $vmname \
  --image $image \
  --admin-username $adminusername \
  --size $size \
  --generate-ssh-keys
